<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVuihn2u\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVuihn2u/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVuihn2u.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVuihn2u\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVuihn2u\appProdProjectContainer([
    'container.build_hash' => 'Vuihn2u',
    'container.build_id' => '2d5c653d',
    'container.build_time' => 1663889649,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVuihn2u');
