<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZhltcxz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZhltcxz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZhltcxz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZhltcxz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZhltcxz\appProdProjectContainer([
    'container.build_hash' => 'Zhltcxz',
    'container.build_id' => '5ff3edbe',
    'container.build_time' => 1663853531,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZhltcxz');
